export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const SELECT_USER = "SELECT_USER";
export const CHANGE_USER_CHECKBOX = "CHANGE_USER_CHECKBOX";
export const REMOVE_USERS = "REMOVE_USERS";
export const UPDATE_USER = "UPDATE_USER";
